version: "3.9"

services:
  mongo-gabysystem:
    image: gabyreload1983/mongo-gabysystem:vx.x.x
    container_name: mongo-gabysystem
    restart: always
    ports:
      - "xxxxx:xxxxx"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - ~/mongo-data:/data/db
